# -*- coding: utf-8 -*-
"""201821018_eum

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEHcJ-u3a8gP8YkT_c-DoGg6p2XvK75O
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

# Bode Plotting
G0 = signal.lti([100], [1])
G1 = signal.lti([1], [1, 2])
G2 = signal.lti([1], [1, 3])
G3 = signal.lti([100], [1, 3, 2])

frequencies = np.logspace(-2, 2, 500)

systems = [G0, G1, G2, G3]
labels = ['Proportional Element', 'Integral Element', 'First-Order Lag Element', 'Overall System']
colors = ['r', 'g', 'b', 'm']

plt.figure(figsize=(12, 8))

plt.subplot(2, 1, 1)
for sys, label, color in zip(systems, labels, colors):
    _, mag, _ = sys.bode(w=frequencies)
    plt.semilogx(frequencies, mag, color=color, label=label)
plt.title('Bode plot')
plt.ylabel('Magnitude [dB]')
plt.legend()

plt.subplot(2, 1, 2)
for sys, label, color in zip(systems, labels, colors):
    _, _, phase = sys.bode(w=frequencies)
    plt.semilogx(frequencies, phase, color=color)
plt.ylabel('Phase [degrees]')
plt.xlabel('Frequency [Hz]')

plt.show()